doc: documentation on generating proofs
dipdup-io/stone-packaging pull request #39
Opened 2024-09-28 23:04 UTC by martinvibes

documentation about generating proofs with a well precise section about docker based setup

2024-09-29 08:43 UTC, dmirgaleev requested changes

2024-09-29 08:43 UTC, dmirgaleev commented on docs/pages/usage/proving.md
> +bazel build //src/main/prover:stone_prover
No need to build, you can use static binaries https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#creating-and-verifying-a-test-proof-using-binaries

2024-09-29 08:43 UTC, dmirgaleev commented on docs/pages/usage/proving.md
> +## Docker-based Setup
Same here, please, try https://github.com/dipdup-io/stone-packaging?tab=readme-ov-file#creating-and-verifying-a-test-proof-using-binaries

2024-09-29 08:43 UTC, dmirgaleev commented on docs/pages/usage/proving.md
> +- **Docker not found:** Ensure Bazel is installed correctly by running `docker --version`. If not installed, follow the [Docker installation guide](https://docs.docker.com/get-started/get-docker/).
```suggestion
- **Docker not found:** Ensure Docker is installed correctly by running `docker --version`. If not installed, follow the [Docker installation guide](https://docs.docker.com/get-started/get-docker/).
```

2024-09-29 08:43 UTC, dmirgaleev commented on docs/pages/usage/proving.md
> +- **Bazel Not Found:** Ensure Bazel is installed correctly by running `bazel --version`. If not installed, follow the [Bazel installation guide](https://bazel.build/install).
Please, make sure you still need Bazel if you use Stone Packaging

2024-09-30 12:42 UTC, martinvibes commented
@dmirgaleev kindly review 
everything is now well described :)

2024-09-30 15:16 UTC, dmirgaleev commented
Unfortunately, the PR seems to be created by ChatGPT without testing. For instance, `cpu_air_prover` doesn't have provided parameters.

2024-09-30 15:16 UTC, closed without merging