doc: create stone deb installation guide
dipdup-io/stone-packaging pull request #53
Opened 2024-10-02 11:14 UTC by od-hunter

#25

2024-10-02 11:24 UTC, od-hunter commented
@dmirgaleev  

this is a draft because am having a minor challenge installing and using the stone package on my local machine.

# what I have done sofar
- I successfull downloaded the stone-prover-linux-x86_64.deb package which is compactable with my system architecture.

- I tried install using  ` sudo dpkg -i stone-prover-linux-x86_64.deb` and 
tried updating the dependencies using `sudo apt-get install -f`

- after the regular installation process trying to use the binary files:
`stone-prover --version` or `/usr/bin/cpu_air_verifier --version` or `/usr/bin/cpu_air_prover --version`   generates "command not found"

**Kindly assist**

2024-10-02 12:20 UTC, dmirgaleev requested changes

2024-10-03 14:44 UTC, od-hunter commented
Hi @dmirgaleev all your corrections have been implement.

and thanks for the pointer it works fine now for performing the test now.

Kindly review

2024-10-03 16:37 UTC, dmirgaleev requested changes

2024-10-03 16:37 UTC, dmirgaleev commented on docs/pages/install/debian.md
> +**Enter your password:** When prompted, enter your user password to proceed with the installation:
I think it's unnecessary step, let's delete that

2024-10-03 16:37 UTC, dmirgaleev commented on docs/pages/install/debian.md
> +cpu_air_prover --out_file=fibonacci_proof.json --private_input_file=fibonacci_private_input.json --public_input_file=fibonacci_public_input.json --prover_config_file=cpu_air_prover_config.json --para
Let's format that like it is here https://github.com/dipdup-io/stone-packaging/blob/master/README.md#creating-and-verifying-a-test-proof-using-binaries

2024-10-03 16:37 UTC, dmirgaleev commented on docs/pages/install/debian.md
> +cpu_air_verifier --in_file=fibonacci_proof.json && echo "Successfully verified example proof."
Let's format that like it is here [master/README.md#creating-and-verifying-a-test-proof-using-binaries](https://github.com/dipdup-io/stone-packaging/blob/master/README.md#creating-and-verifying-a-test-proof-using-binaries)

2024-10-03 22:34 UTC, od-hunter commented
Requested change has been implemented @dmirgaleev

2024-10-04 11:51 UTC, dmirgaleev requested changes

2024-10-04 11:51 UTC, dmirgaleev commented on docs/pages/install/debian.md
> +Download the latest .deb package from the Stone Packaging Releases page to the /tmp directory. Alternatively, you can use `wget` to download it directly.
What does that mean? I believe there's only one way.

2024-10-04 11:51 UTC, dmirgaleev commented on docs/pages/install/debian.md
> +## Step 3: Implement Run Test Proof
As I said, that will be covered separately. Please, remove

2024-10-04 14:30 UTC, od-hunter commented
@dmirgaleev , please review.

2024-10-05 08:37 UTC, merged