feat: Stone Prover config
dipdup-io/stone-packaging pull request #69
Opened 2024-10-05 20:37 UTC by Jemiiah

solves issue : #29

2024-10-06 14:36 UTC, Jemiiah commented
alright ser

2024-10-07 15:39 UTC, dmirgaleev requested changes

2024-10-07 15:39 UTC, dmirgaleev commented on docs/dist/.vocs/icons/arrow-diagonal.svg
Please, delete all unnecessary files, only one md file should be in the PR.

2024-10-07 15:39 UTC, dmirgaleev commented on docs/pages/usage/configuration.md
> +{
Please, fix formatting here (```json for json code blocks)

2024-10-07 15:39 UTC, dmirgaleev commented on docs/pages/usage/configuration.md
> +{
Please, fix formatting

2024-10-07 15:39 UTC, dmirgaleev commented on docs/pages/usage/configuration.md
> +{
Please, fix formatting

2024-10-07 20:08 UTC, closed without merging