doc: Install Stone from sources
dipdup-io/stone-packaging pull request #70
Opened 2024-10-06 06:17 UTC by MullerTheScientist

closes #22

2024-10-06 14:17 UTC, dmirgaleev requested changes

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +cd /tmp/stone-prover || exit
Why do you do `|| exit` here?

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +### Linux
If it's a Linux related guid, why `### Linux` after `## Install Dependencies`?

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +wget "https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-$os-$arch"
For linux the only suitable binary is https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64. That means you can simplify that

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +os=$(uname | tr '[:upper:]' '[:lower:]')
You don't need that for building from sources

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +# Homebrew is most likely already installed. If not, uncomment the next line.
Please, convert that for an explanation, instead of the line from the script

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +cd /tmp/stone-prover || exit
```suggestion
cd /tmp/stone-prover

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +bazelisk build --cpu=$arch //...
```suggestion
bazelisk build //...
```

2024-10-06 14:17 UTC, dmirgaleev commented on docs/pages/install/sources.md
> +bazelisk test --cpu=$arch //...
```suggestion
bazelisk test //...
```

2024-10-07 14:55 UTC, MullerTheScientist commented
The requested changes have been implemented.

2024-10-07 17:17 UTC, dmirgaleev approved these changes

2024-10-07 17:18 UTC, merged